# Controller for the wheels
robot_wheel_controller:
  type: "diff_drive_controller/DiffDriveController"
  publish_rate: 50
  velocity_commands_topic: "/cmd_vel"
  joints:
    - left_wheel_joint  # Make sure this matches the joint name in the URDF
    - right_wheel_joint # Same here
  gains:
    left_wheel_joint: {p: 10.0, i: 0.01, d: 1.0}
    right_wheel_joint: {p: 10.0, i: 0.01, d: 1.0}
  constraints:
    goal_time: 0.6
    left_wheel_joint: {trajectory: 0.05, goal: 0.02} 
    right_wheel_joint: {trajectory: 0.05, goal: 0.02}
  state_publish_rate: 50
  action_monitor_rate: 10
  default_velocities: [0.0, 0.0]


# ----- This is a test code snippet for gripper.
# Controller for the gripper
# robot_gripper_controller:
#   type: "effort_controllers/GripperActionController"
#   joint: "right_gripper_joint"  # Replace with your gripper joint name
#   action_name: "gripper_action"
#   goal_tolerance: 0.01          # Tolerance for the goal position (in meters or radians)
#   grip_force: 10.0              # Force applied by the gripper (in Newtons)
#   stiffness: 100.0              # Stiffness of the gripper (in Newtons per meter or similar units)
#   damping: 10.0                 # Damping of the gripper (in Newton-seconds per meter or similar units)
#   min_effort: 0.0               # Minimum effort for the gripper (in Newtons)
#   max_effort: 50.0              # Maximum effort for the gripper (in Newtons)
#   action_time_out: 5.0          # Timeout for the action in seconds

  # type: "effort_controllers/JointPositionController"
  # joint: "right_gripper_joint"
  # pid: {p: 50.0, i: 0.01, d: 1.0}

# Joint state controller to publish joint states
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
